services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=db_ag_invest
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"